services:
  - type: web
    name: civl3704
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 6 --worker-class gthread --timeout 120
    healthCheckPath: /ping
    envVars:
      - key: TFNSW_API_KEY
        sync: false
      - key: TFNSW_GTFS_RT_URL
        value: https://api.transport.nsw.gov.au/v1/gtfs/realtime/buses
      - key: PYTHON_VERSION
        value: 3.11.0